### ISSUE TITLE
App crashes on launch after crashing during session viewing

### ISSUE THREAD

**Issue by ZacSweers** [paug/AndroidMakersApp-iOS#15]
Apologies as I don't have any other context beyond that. I was scrolling through the current schedule when it crashed, and now it crashes on startup when I try to reopen since.

https://user-images.githubusercontent.com/1361086/165064027-cfdd633f-9a6f-44d9-a70c-d151613e9508.MP4

**Comment by djavan-bertrand** [comment]
Hi Zac, 
Thanks a lot for the report! It is fixed right now but unfortunately you might have to delete and reinstall the app. I'm really sorry about that.

**Comment by madisp** [comment]
> Hi Zac, Thanks a lot for the report! It is fixed right now but unfortunately you might have to delete and reinstall the app. I'm really sorry about that.

can confirm that it works for me again, thanks for the quick fix!

**Comment by djavan-bertrand** [comment]
Fixed in https://github.com/paug/AndroidMakersApp-iOS/commit/64b68351f20ebc84d7b761091534504a3b66b3e6
